# Generated by Django 5.1.2 on 2025-03-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_comment_author_alter_commentreaction_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postshare',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
